let firstNameId = 'first-name';
let lastNameId = 'last-name';
let addressId = 'address';
let cityListId = 'city-list';
let hobbiesId = 'hobbies';
let avatarWrapperId = 'avatar-wrapper';
let avatarId = 'avatar';

let firstNameEl = document.getElementById(firstNameId);
let lastNameEl = document.getElementById(lastNameId);
let addressEl = document.getElementById(addressId);
let cityListEl = document.getElementById(cityListId);
let hobbiesEl = document.getElementById(hobbiesId);
let avatarWrapperEl = document.getElementById(avatarWrapperId);
let avatarEl = document.getElementById(avatarId);
//window.alert(firstNameEl.value);
//window.alert(lastNameEl.value);
//window.alert(addressEl.value);
//window.alert(cityListEl.value);
//window.alert(hobbiesEl.value);
//window.alert(avatarEl.innerHTML);
//window.alert(hobbiesEl.innerHTML);
//window.alert(cityListEl.innerHTML);
//window.alert(avatarEl.alt);
//window.alert(avatarEl.src);
firstNameEl.value = 'Pablo';
//firstNameEl.className = 'Pablo';
lastNameEl.value = 'Pablito';
// window.alert(firstNameEl.value);
//window.alert(lastNameEl.value);
window.alert(lastNameEl.className);
lastNameEl.className = 'last-name default-input error-input';
avatarEl.src = 'https://static.wikia.nocookie.net/enanimanga/images/f/fe/Sweet_Punishment.jpg/revision/latest/smart/width/53/height/53?cb=20180418073321';
avatarEl.title = 'SUPA DUPA AVA';
lastNameEl.title = 'Wrong last name'
cityListEl.value = 'Kiev';
hobbiesEl.value = 'Drunkin stelka';
avatarWrapperEl.innerHTML = '<ul id=\'list\'><li>1</li><li>2</li><ul>';
let listId = 'list';
let numberList = document.getElementById(listId);
window.alert(numberList.innerHTML);